version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Temporal2021+
      MYSQL_DATABASE: testexam
    ports:
      - "3307:3306"  # Change the host port to 3307
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: 2340238940234
      DATABASE_USER: root
      DATABASE_PASSWORD: Temporal2021+
      DATABASE_HOST: db
      DATABASE: testexam
      OTEL_EXPORTER_OTLP_HEADERS: signoz-access-token=a893d527-40c9-406b-8f26-a0b8b3547b06
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
